close all
clc
clear
load('Jr_bifurcation_2population_twosameinput_k25_final.mat')
% start plotting


singlecolfigwidth = 19;
doublecolfigwidth = 34;

singlecolfigheight = 22;
doublecolfigheight = 27;

fontsize = 9;       % pt
fontname = 'ariel';

markersize = 2;
linewidth = 2;

fig1 = figure('paperunits','centimeters',...
    'paperposition',[0 0 singlecolfigwidth, singlecolfigheight],...
    'units','centimeters',...
    'papersize',[singlecolfigwidth, singlecolfigheight],...
    'position',[5, 5, singlecolfigwidth, singlecolfigheight],...
    'renderer','painters');


ax1 = axes('parent',fig1,...
    'units','centimeters',...
    'position',[2.5, 1, 14, 14]);
hold on

xlabel(ax1,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax1,'EEG Signal \it y(t) \rm (mV)',...
    'fontsize',fontsize,...
    'fontname',fontname)
set(ax1,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[-60 0 200 350],...
    'ytick',[0 12],...
    'xlim',[-60 350],...
    'ylim',[0 12])

%%
%/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\

fig2 = figure('paperunits','centimeters',...
    'paperposition',[0 0 doublecolfigwidth, doublecolfigheight],...
    'units','centimeters',...
    'papersize',[doublecolfigwidth, doublecolfigheight],...
    'position',[1, 1, doublecolfigwidth, doublecolfigheight],...
    'renderer','painters');

ax5 = axes('parent',fig2,...
    'units','centimeters',...
    'position',[2, 7, 14, 14]);
hold on

xlabel(ax5,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax5,'EEG Signal \it y_a(t) \rm (mV)',...
    'fontsize',fontsize,...
    'fontname',fontname)
set(ax5,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[-60 0 200 350],...
    'ytick',[-4 4 10],...
    'xlim',[-48 120],...
    'ylim',[-4 10])
%>>>>>>>
ax6 = axes('parent',fig2,...
    'units','centimeters',...
    'position',[18, 7, 14, 14]);
hold on

xlabel(ax6,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax6,'',...
    'fontsize',fontsize,...
    'fontname',fontname)
set(ax6,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[-60 0 200 350],...
    'ytick',[-4 4 10],...
    'xlim',[-48 120],...
    'ylim',[-4 10])
%>>>>>>>
ax9 = axes('parent',fig2,...
    'units','centimeters',...
    'position',[4, 1, 5, 4]);
hold on

xlabel(ax9,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax9,'EEG Signal \it y_a(t) \rm (mV) ',...
    'fontsize',fontsize,...
    'fontname',fontname)
title(ax9,'1')
set(ax9,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[-16 -10],...
    'ytick',[5.5 6.5],...
    'xlim',[-17 -10],...
    'ylim',[5.5 6.5])
%>>>>>>>
ax10 = axes('parent',fig2,...
    'units','centimeters',...
    'position',[12, 1, 5, 4]);
hold on

xlabel(ax10,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax10,'',...
    'fontsize',fontsize,...
    'fontname',fontname)
title(ax10,'2')
set(ax10,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[90 105],...
    'ytick',[6 7.5],...
    'xlim',[86 107],...
    'ylim',[5.8 7.8])
%>>>>>>>
ax11 = axes('parent',fig2,...
    'units','centimeters',...
    'position',[20, 1, 5, 4]);
hold on

xlabel(ax11,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax11,'',...
    'fontsize',fontsize,...
    'fontname',fontname)
title(ax11,'3')
set(ax11,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[90 110],...
    'ytick',[1 3],...
    'xlim',[86 112],...
    'ylim',[0.8 3.8])
%>>>>>>>
ax12 = axes('parent',fig2,...
    'units','centimeters',...
    'position',[28, 1, 5, 4]);
hold on

xlabel(ax12,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax12,'',...
    'fontsize',fontsize,...
    'fontname',fontname)
title(ax12,'3-1')
set(ax12,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[96.61 96.65],...
    'ytick',[3.2 3.4],...
    'xlim',[96.61 96.65],...
    'ylim',[3.19 3.44])
%/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
%%
fig3 = figure('paperunits','centimeters',...
    'paperposition',[0 0 doublecolfigwidth, 24],...
    'units','centimeters',...
    'papersize',[doublecolfigwidth, 24],...
    'position',[0, 0, doublecolfigwidth, 24],...
    'renderer','painters');

ax13 = axes('parent',fig3,...
    'units','centimeters',...
    'position',[2, 8, 14, 14]);
hold on

xlabel(ax13,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax13,'EEG Signal \it y_a(t) \rm (mV)',...
    'fontsize',fontsize,...
    'fontname',fontname)
set(ax13,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[-40 40 120],...
    'ytick',[-4 2 8],...
    'xlim',[-50 120],...
    'ylim',[-4 8])
%>>>>>>>
ax14 = axes('parent',fig3,...
    'units','centimeters',...
    'position',[18, 8, 14, 14]);
hold on

xlabel(ax14,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax14,'',...
    'fontsize',fontsize,...
    'fontname',fontname)
set(ax14,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[-40 40 120],...
    'ytick',[-4 2 8],...
    'xlim',[-50 120],...
    'ylim',[-4 8])
%>>>>>>>
ax15 = axes('parent',fig3,...
    'units','centimeters',...
    'position',[4, 2, 5, 4]);
hold on

xlabel(ax15,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax15,'EEG Signal \it y_a(t) \rm (mV)',...
    'fontsize',fontsize,...
    'fontname',fontname)
title(ax15,'1')
set(ax15,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[-45 -35 -20],...
    'ytick',[-3.4 -3 -2.4],...
    'xlim',[-46 -18],...
    'ylim',[-3.45 -2.4])
%>>>>>>>
ax16 = axes('parent',fig3,...
    'units','centimeters',...
    'position',[12, 2, 5, 4]);
hold on

xlabel(ax16,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax16,'',...
    'fontsize',fontsize,...
    'fontname',fontname)
title(ax16,'2')
set(ax16,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[92 102 112],...
    'ytick',[1.4 2.4 3.4],...
    'xlim',[92 112],...
    'ylim',[1.3 3.4])
%>>>>>>>
ax17 = axes('parent',fig3,...
    'units','centimeters',...
    'position',[20, 2, 5, 4]);
hold on

xlabel(ax17,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax17,' ',...
    'fontsize',fontsize,...
    'fontname',fontname)
title(ax17,'3')
set(ax17,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[-46 -40 -32],...
    'ytick',[4.9 5.3 5.7],...
    'xlim',[-46.5 -32],...
    'ylim',[4.8 5.8])
%>>>>>>>
ax18= axes('parent',fig3,...
    'units','centimeters',...
    'position',[28, 2, 5, 4]);
hold on

xlabel(ax18,'Input Firing Rate \it p(t) \rm	(Aps/s)',...
    'fontsize',fontsize,...
    'fontname',fontname)
ylabel(ax18,'',...
    'fontsize',fontsize,...
    'fontname',fontname)
title(ax18,'4')
set(ax18,'fontname',fontname,...
    'fontsize',fontsize,...
    'box','off',...
    'xtick',[85 95 105],...
    'ytick',[6.7 6.8 6.9],...
    'xlim',[81 107],...
    'ylim',[6.65 6.9])



%%


%--------------------------------------------------------------------------
% figure (1)
% hold on
% %xlim([-100 400])

plot( ax1,...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    );
hold on



% Second brunch of equilibruim points

figure (501)
hold on
plot( ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )

plot( ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--r'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'b'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )

figure()

plot(x3_1_1,num_unstable_eigenvalue_1)

% plot(x3_1(change_stability_index_coupling(1):change_stability_index_coupling(end)),num_unstable_eigenvalue(change_stability_index_coupling(1):change_stability_index_coupling(end)))
xlabel('y_1')
ylabel('number of unstable eigenvalues of Jacobian matrix')





%second population

figure (502)
hold on

plot( ...
    p2(1:change_stability_index_coupling_1(1)),x3_2_2(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_2_2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_2_2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--r'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_2_2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'b'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_2_2(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )

figure()

plot(x3_2_2,num_unstable_eigenvalue_1)

% plot(x3_1(change_stability_index_coupling(1):change_stability_index_coupling(end)),num_unstable_eigenvalue(change_stability_index_coupling(1):change_stability_index_coupling(end)))
xlabel('y_2')
ylabel('number of unstable eigenvalues of Jacobian matrix')


%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^




plot(ax5, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax5,...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )


plot(ax13, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax13,...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )


plot(ax15, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax15, ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )

%


plot(ax16, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax16, ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )



%


plot(ax17, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax17, ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )


%


plot(ax18, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax18, ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )
xlim([75 120])
ylim([5 8])











plot(ax5, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot( ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )
xlim([-48 120])




plot(ax10,...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax10, ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )


%


plot(ax9, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax9, ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )



%


plot(ax11, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax11,...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )


%


plot(ax12,...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax12, ...
    p2(1:change_stability_index_coupling_1(1)),x3_1_1(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_1_1(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_1_1(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_1_1(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_1_1(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )


%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



plot(ax6, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_2(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_2(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_2(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax6, ...
    p2(1:change_stability_index_coupling_1(1)),x3_2_2(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_2_2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_2_2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_2_2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_2_2(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )

plot(ax14, ...
    p1(1:change_stability_index_coupling(1)),x3_1(1:change_stability_index_coupling(1)),'k' ...
    ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_2(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
    ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_2(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
    ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_2(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
    ,p1(change_stability_index_coupling(4)+1:end),x3_1(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
    )
% Second brunch of equilibruim points

plot(ax14, ...
    p2(1:change_stability_index_coupling_1(1)),x3_2_2(1:change_stability_index_coupling_1(1)),'--r' ...
    ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_2_2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
    ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_2_2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
    ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_2_2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
    ,p2(change_stability_index_coupling_1(4)+1:end),x3_2_2(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
    )

% plot(ax15, ...
%     p1(1:change_stability_index_coupling(1)),x3_2(1:change_stability_index_coupling(1)),'k' ...
%     ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_2(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
%     ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_2(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
%     ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_2(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
%     ,p1(change_stability_index_coupling(4)+1:end),x3_2(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
%     )
% % Second brunch of equilibruim points
% 
% plot(ax15, ...
%     p2(1:change_stability_index_coupling_1(1)),x3_2_2(1:change_stability_index_coupling_1(1)),'--r' ...
%     ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_2_2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
%     ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_2_2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
%     ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_2_2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
%     ,p2(change_stability_index_coupling_1(4)+1:end),x3_2_2(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
%     )
% %
% 
% plot(ax16, ...
%     p1(1:change_stability_index_coupling(1)),x3_2(1:change_stability_index_coupling(1)),'k' ...
%     ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_2(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
%     ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_2(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
%     ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_2(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
%     ,p1(change_stability_index_coupling(4)+1:end),x3_2(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
%     )
% % Second brunch of equilibruim points
% 
% plot(ax16, ...
%     p2(1:change_stability_index_coupling_1(1)),x3_2_2(1:change_stability_index_coupling_1(1)),'--r' ...
%     ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_2_2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
%     ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_2_2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
%     ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_2_2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
%     ,p2(change_stability_index_coupling_1(4)+1:end),x3_2_2(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
%     )
% 
% 
% 
% %
% 
% plot(ax17, ...
%     p1(1:change_stability_index_coupling(1)),x3_2(1:change_stability_index_coupling(1)),'k' ...
%     ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_2(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
%     ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_2(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
%     ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_2(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
%     ,p1(change_stability_index_coupling(4)+1:end),x3_2(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
%     )
% % Second brunch of equilibruim points
% 
% plot(ax17, ...
%     p2(1:change_stability_index_coupling_1(1)),x3_2_2(1:change_stability_index_coupling_1(1)),'--r' ...
%     ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_2_2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
%     ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_2_2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
%     ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_2_2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
%     ,p2(change_stability_index_coupling_1(4)+1:end),x3_2_2(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
%     )
% 
% 
% %
% 
% plot(ax18, ...
%     p1(1:change_stability_index_coupling(1)),x3_2(1:change_stability_index_coupling(1)),'k' ...
%     ,p1(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),x3_2(change_stability_index_coupling(1)+1:change_stability_index_coupling(2)),'--k' ...
%     ,p1(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),x3_2(change_stability_index_coupling(2)+1:change_stability_index_coupling(3)),'k'...
%     ,p1(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),x3_2(change_stability_index_coupling(3)+1:change_stability_index_coupling(4)),'--k'...
%     ,p1(change_stability_index_coupling(4)+1:end),x3_2(change_stability_index_coupling(4)+1:end),'k','LineWidth',1.5 ...
%     )
% % Second brunch of equilibruim points
% 
% plot(ax18, ...
%     p2(1:change_stability_index_coupling_1(1)),x3_2_2(1:change_stability_index_coupling_1(1)),'--r' ...
%     ,p2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),x3_2_2(change_stability_index_coupling_1(1)+1:change_stability_index_coupling_1(2)),'b' ...
%     ,p2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),x3_2_2(change_stability_index_coupling_1(2)+1:change_stability_index_coupling_1(3)),'--b'...
%     ,p2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),x3_2_2(change_stability_index_coupling_1(3)+1:change_stability_index_coupling_1(4)),'r'...
%     ,p2(change_stability_index_coupling_1(4)+1:end),x3_2_2(change_stability_index_coupling_1(4)+1:end),'--r','LineWidth',1.5 ...
%     )
%<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
% %                             Plot All figures together      
%<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

%load Jr_bifurcation_2population_twosameinput_k25_test.mat 



% plot different limit cycles corresponded to the first population!
clear mag_max mag_min inputp
[nr,nc]=size(xlc1);
for ii=1:nc
    mag_max(ii)=max(xlc1(3:16:nr-1,ii));
    mag_min(ii)=min(xlc1(3:16:nr-1,ii));
    inputp(ii)=xlc1(end,ii);
end
%hold on
plot(ax1,inputp,mag_max,'Color',[0.2 0.5 0.5],'linewidth',1.5)
plot(ax1,inputp,mag_min,'Color',[0.2 0.5 0.5],'linewidth',1.5)

clear mag_max mag_min inputp
[nr,nc]=size(xlc2);
for ii=1:nc
    mag_max(ii)=max(xlc2(3:16:nr-1,ii));
    mag_min(ii)=min(xlc2(3:16:nr-1,ii));
    inputp(ii)=xlc2(end,ii);
end
hold on
plot(ax1,inputp,mag_max,'Color',[0.5 0.2 0.5],'linewidth',1.5)
plot(ax1,inputp,mag_min,'Color',[0.5 0.2 0.5],'linewidth',1.5)

% clear mag_max mag_min inputp
% figure(500)
% [nr,nc]=size(xlc3);
% for ii=1:nc
%     mag_max(ii)=max(xlc3(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc3(3:16:nr-1,ii));
%     inputp(ii)=xlc3(end,ii);
% end
% hold on
% plot(inputp,mag_max,'linewidth',2)
% plot(inputp,mag_min,'linewidth',2)
% %
clear mag_max mag_min inputp
[nr,nc]=size(xlc4);
for ii=1:nc
    mag_max(ii)=max(xlc4(3:16:nr-1,ii));
    mag_min(ii)=min(xlc4(3:16:nr-1,ii));
    inputp(ii)=xlc4(end,ii);
end
hold on
plot(ax1,inputp(1:500),mag_max(1:500),'Color',[0.3 0.3 0.8],'linestyle','--','linewidth',1.5)
plot(ax1,inputp(500:end),mag_max(500:end),'Color',[1 0 0],'linewidth',1.5)

plot(ax1,inputp(1:500),mag_min(1:500),'Color',[0.3 0.3 0.8],'linestyle','--','linewidth',1.5)
plot(ax1,inputp(500:end),mag_min(500:end),'Color',[1 0 0],'linewidth',1.5)

%
clear mag_max mag_min inputp
[nr,nc]=size(xlc13);
for ii=1:nc
    mag_max(ii)=max(xlc13(3:16:nr-1,ii));
    mag_min(ii)=min(xlc13(3:16:nr-1,ii));
    inputp(ii)=xlc13(end,ii);
end
hold on
plot(ax1,inputp(1:500),mag_max(1:500),'Color',[1 0 1],'linestyle','--','linewidth',1.5)
plot(ax1,inputp(500:end),mag_max(500:end),'Color',[0.5 0.5 0.5],'linewidth',1.5)

plot(ax1,inputp(1:500),mag_min(1:500),'Color',[1 0 1],'linestyle','--','linewidth',1.5)
plot(ax1,inputp(500:end),mag_min(500:end),'Color',[0.5 0.5 0.5],'linewidth',1.5)


% gt = gtext('1');
hold on
%subcritical
g1=plot(ax1,-21.43,5.903,'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax1,-14.46,5.982,'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2)
%supercritical
g2=plot(ax1,93.4,6.81,'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax1,71.566,6.668,'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2)
plot(ax1,298.6,8.033,'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2)
plot(ax1,313.4,8.122,'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2)
%Homoclinic and Saddle node
g3=plot(ax1,135.4,3.422,'Color',[0 0 0],'Marker','d','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax1,125.7,3.487,'Color',[0 0 0],'Marker','d','MarkerEdgeColor',[0 0 0],'linewidth',2)
plot(ax1,136.2,11.72,'Color',[0 0 0],'Marker','d','MarkerEdgeColor',[0 0 0],'linewidth',2)
plot(ax1,125.70,11.32,'Color',[0 0 0],'Marker','d','MarkerEdgeColor',[0 0 0],'linewidth',2)
plot(ax1,112,2.556,'Color',[0 0 0],'Marker','d','MarkerEdgeColor',[0 0 0],'linewidth',2)
%  Saddle saddle
g4=plot(ax1,-46.19,5.376,'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);
gleg1=legend([g1 g2 g3 g4],'Subcritical Hopf','Supercritical Hopf','Saddle-Node','Saddle-Saddle');
legend boxoff
set(gleg1,'Location','SouthEast')
set(gleg1,'Interpreter','none')



% xlc5=xlc8=xlx9=xlc12
% xlc6=xlc7=xlx10=xlc11

clear mag_max mag_min inputp
[nr,nc]=size(xlc5);
for ii=1:nc
    mag_max(ii)=max(xlc5(3:16:nr-1,ii));
    mag_min(ii)=min(xlc5(3:16:nr-1,ii));
    inputp(ii)=xlc5(end,ii);
end

plot(ax5,inputp,mag_max,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1.5)
plot(ax5,inputp,mag_min,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1.5)



plot(ax10,inputp,mag_max,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1)
plot(ax10,inputp,mag_min,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1)


plot(ax9,inputp,mag_max,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1)
plot(ax9,inputp,mag_min,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1)


plot(ax11,inputp,mag_max,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1)
plot(ax11,inputp,mag_min,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1)


plot(ax12,inputp,mag_max,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1)
plot(ax12,inputp,mag_min,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1)
%

clear mag_max mag_min inputp
[nr,nc]=size(xlc6);
for ii=1:nc
    mag_max(ii)=max(xlc6(3:16:nr-1,ii));
    mag_min(ii)=min(xlc6(3:16:nr-1,ii));
    inputp(ii)=xlc6(end,ii);
end
plot(ax5,inputp,mag_max,'Color',[0.6 0 1],'linewidth',1.5)
plot(ax5,inputp,mag_min,'Color',[0.6 0 1],'linewidth',1.5)



plot(ax10,inputp,mag_max,'Color',[0.6 0 1],'linestyle','--','linewidth',1)
plot(ax10,inputp,mag_min,'Color',[0.6 0 1],'linestyle','--','linewidth',1)


plot(ax9,inputp,mag_max,'Color',[0.6 0 1],'linestyle','--','linewidth',1)
plot(ax9,inputp,mag_min,'Color',[0.6 0 1],'linestyle','--','linewidth',1)


plot(ax11,inputp,mag_max,'Color',[0.6 0 1],'linestyle','--','linewidth',1)
plot(ax11,inputp,mag_min,'Color',[0.6 0 1],'linestyle','--','linewidth',1)


plot(ax12,inputp,mag_max,'Color',[0.6 0 1],'linestyle','--','linewidth',1)
plot(ax12,inputp,mag_min,'Color',[0.6 0 1],'linestyle','--','linewidth',1)
%xlc6=xlc7
% clear mag_max mag_min inputp
% figure(250)
% [nr,nc]=size(xlc7);
% for ii=1:nc
%     mag_max(ii)=max(xlc7(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc7(3:16:nr-1,ii));
%     inputp(ii)=xlc7(end,ii);
% end
% hold on
% plot(inputp,mag_max,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% %
%xlc8=xlc5
% clear mag_max mag_min inputp
% figure(250)
% [nr,nc]=size(xlc8);
% for ii=1:nc
%     mag_max(ii)=max(xlc8(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc8(3:16:nr-1,ii));
%     inputp(ii)=xlc8(end,ii);
% end
% hold on
% plot(inputp,mag_max,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% %
clear mag_max mag_min inputp
[nr,nc]=size(xlc9);
for ii=1:nc
    mag_max(ii)=max(xlc9(3:16:nr-1,ii));
    mag_min(ii)=min(xlc9(3:16:nr-1,ii));
    inputp(ii)=xlc9(end,ii);
end
% plot(inputp,mag_max,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1.5)
 
plot(ax5,inputp(1:450),mag_max(1:450),'Color',[1 0.5 0.5],'linestyle','--','linewidth',1.5)
plot(ax5,inputp(1:450),mag_min(1:450),'Color',[1 0.5 0.5],'linestyle','--','linewidth',1.5)


plot(ax10,inputp,mag_max,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1)
plot(ax10,inputp,mag_min,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1)


plot(ax9,inputp,mag_max,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1)
plot(ax9,inputp,mag_min,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1)


plot(ax11,inputp,mag_max,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1)
plot(ax11,inputp,mag_min,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1)


plot(ax12,inputp,mag_max,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1)
plot(ax12,inputp,mag_min,'Color',[1 0.5 0.5],'linestyle','--','linewidth',1)


%
clear mag_max mag_min inputp
[nr,nc]=size(xlc10);
for ii=1:nc
    mag_max(ii)=max(xlc10(3:16:nr-1,ii));
    mag_min(ii)=min(xlc10(3:16:nr-1,ii));
    inputp(ii)=xlc10(end,ii);
end
plot(ax5,inputp,mag_max,'Color',[0.5 1 0.5],'linewidth',1.5)
plot(ax5,inputp,mag_min,'Color',[0.5 1 0.5],'linewidth',1.5)


plot(ax10,inputp,mag_max,'Color',[0.5 1 0.5],'linestyle','--','linewidth',1)
plot(ax10,inputp,mag_min,'Color',[0.5 1 0.5],'linestyle','--','linewidth',1)


plot(ax9,inputp,mag_max,'Color',[0.5 1 0.5],'linestyle','--','linewidth',1)
plot(ax9,inputp,mag_min,'Color',[0.5 1 0.5],'linestyle','--','linewidth',1)


plot(ax11,inputp,mag_max,'Color',[0.5 1 0.5],'linestyle','--','linewidth',1)
plot(ax11,inputp,mag_min,'Color',[0.5 1 0.5],'linestyle','--','linewidth',1)


plot(ax12,inputp,mag_max,'Color',[0.5 1 0.5],'linestyle','--','linewidth',1)
plot(ax12,inputp,mag_min,'Color',[0.5 1 0.5],'linestyle','--','linewidth',1)

%
% xlc11=xlc10
% clear mag_max mag_min inputp
% figure(250)
% [nr,nc]=size(xlc11);
% for ii=1:nc
%     mag_max(ii)=max(xlc11(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc11(3:16:nr-1,ii));
%     inputp(ii)=xlc11(end,ii);
% end
% hold on
% plot(inputp,mag_max,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
%
% clear mag_max mag_min inputp
% figure(250)
% [nr,nc]=size(xlc12);
% for ii=1:nc
%     mag_max(ii)=max(xlc12(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc12(3:16:nr-1,ii));
%     inputp(ii)=xlc12(end,ii);
% end
% hold on
% plot(inputp,mag_max,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)


%subcritical
m1=plot(ax5,x_3(17,s_3(7).index),x_3(3,s_3(7).index),'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(12).index),x_3(3,s_3(12).index),'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(18).index),x_3(3,s_3(18).index),'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(23).index),x_3(3,s_3(23).index),'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);

%supercritical

m2=plot(ax5,x_3(17,s_3(8).index),x_3(3,s_3(8).index),'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(10).index),x_3(3,s_3(10).index),'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(20).index),x_3(3,s_3(20).index),'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(22).index),x_3(3,s_3(22).index),'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);

%  Saddle saddle
m4=plot(ax5,x_3(17,s_3(6).index),x_3(3,s_3(6).index),'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(9).index),x_3(3,s_3(9).index),'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(21).index),x_3(3,s_3(21).index),'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax5,x_3(17,s_3(24).index),x_3(3,s_3(24).index),'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);

gleg1=legend([m1 m2 m4],'Subcritical Hopf','Supercritical Hopf','Saddle-Saddle');
legend boxoff
set(gleg1,'Location','SouthEast')
set(gleg1,'Interpreter','none')




%^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


clear mag_max mag_min inputp
[nr,nc]=size(xlc5);
for ii=1:nc
    mag_max(ii)=max(xlc5(11:16:nr-1,ii));
    mag_min(ii)=min(xlc5(11:16:nr-1,ii));
    inputp(ii)=xlc5(end,ii);
end
plot(ax6,inputp,mag_max,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1.5)
plot(ax6,inputp,mag_min,'Color',[0.5 0.8 0.5],'linestyle','--','linewidth',1.5)
%

clear mag_max mag_min inputp
[nr,nc]=size(xlc6);
for ii=1:nc
    mag_max(ii)=max(xlc6(11:16:nr-1,ii));
    mag_min(ii)=min(xlc6(11:16:nr-1,ii));
    inputp(ii)=xlc6(end,ii);
end
plot(ax6,inputp,mag_max,'Color',[0.6 0 1],'linewidth',1.5)
plot(ax6,inputp,mag_min,'Color',[0.6 0 1],'linewidth',1.5)

%xlc6=xlc7
% clear mag_max mag_min inputp
% figure(250)
% [nr,nc]=size(xlc7);
% for ii=1:nc
%     mag_max(ii)=max(xlc7(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc7(3:16:nr-1,ii));
%     inputp(ii)=xlc7(end,ii);
% end
% hold on
% plot(inputp,mag_max,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% %
%xlc8=xlc5
% clear mag_max mag_min inputp
% figure(250)
% [nr,nc]=size(xlc8);
% for ii=1:nc
%     mag_max(ii)=max(xlc8(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc8(3:16:nr-1,ii));
%     inputp(ii)=xlc8(end,ii);
% end
% hold on
% plot(inputp,mag_max,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% %
clear mag_max mag_min inputp
[nr,nc]=size(xlc9);
for ii=1:nc
    mag_max(ii)=max(xlc9(11:16:nr-1,ii));
    mag_min(ii)=min(xlc9(11:16:nr-1,ii));
    inputp(ii)=xlc9(end,ii);
end
plot(ax6,inputp(1:450),mag_max(1:450),'Color',[1 0.5 0.5],'linestyle','--','linewidth',1.5)
plot(ax6,inputp(1:450),mag_min(1:450),'Color',[1 0.5 0.5],'linestyle','--','linewidth',1.5)
%
clear mag_max mag_min inputp
[nr,nc]=size(xlc10);
for ii=1:nc
    mag_max(ii)=max(xlc10(11:16:nr-1,ii));
    mag_min(ii)=min(xlc10(11:16:nr-1,ii));
    inputp(ii)=xlc10(end,ii);
end
plot(ax6,inputp,mag_max,'Color',[0.5 1 0.5],'linewidth',1.5)
plot(ax6,inputp,mag_min,'Color',[0.5 1 0.5],'linewidth',1.5)
%
% xlc11=xlc10
% clear mag_max mag_min inputp
% figure(250)
% [nr,nc]=size(xlc11);
% for ii=1:nc
%     mag_max(ii)=max(xlc11(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc11(3:16:nr-1,ii));
%     inputp(ii)=xlc11(end,ii);
% end
% hold on
% plot(inputp,mag_max,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
%
% clear mag_max mag_min inputp
% figure(250)
% [nr,nc]=size(xlc12);
% for ii=1:nc
%     mag_max(ii)=max(xlc12(3:16:nr-1,ii));
%     mag_min(ii)=min(xlc12(3:16:nr-1,ii));
%     inputp(ii)=xlc12(end,ii);
% end
% hold on
% plot(inputp,mag_max,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)
% plot(inputp,mag_min,'Color',[0.5 0.5 0.5],'linestyle','--','linewidth',1.5)



% gt = gtext('1');
%subcritical
m1=plot(ax6,x_3(17,s_3(7).index),x_3(3,s_3(7).index),'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(12).index),x_3(3,s_3(12).index),'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(18).index),x_3(3,s_3(18).index),'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(23).index),x_3(3,s_3(23).index),'Color',[0 0 0],'Marker','s','MarkerEdgeColor',[0 0 0],'linewidth',2);

%supercritical

m2=plot(ax6,x_3(17,s_3(8).index),x_3(3,s_3(8).index),'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(10).index),x_3(3,s_3(10).index),'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(20).index),x_3(3,s_3(20).index),'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(22).index),x_3(3,s_3(22).index),'Color',[0 0 0],'Marker','o','MarkerEdgeColor',[0 0 0],'linewidth',2);

%  Saddle saddle
m4=plot(ax6,x_3(17,s_3(6).index),x_3(3,s_3(6).index),'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(9).index),x_3(3,s_3(9).index),'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(21).index),x_3(3,s_3(21).index),'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);
plot(ax6,x_3(17,s_3(24).index),x_3(3,s_3(24).index),'Color',[0 0 0],'Marker','v','MarkerEdgeColor',[0 0 0],'linewidth',2);

















